<template>
  <div class="temporary-identities">
    <section class="country-panel">
      <div class="panel-header"><h2>国家</h2><div class="panel-actions"><el-tooltip content="刷新"><el-button link @click="loadCountries"><Icon icon="ion:reload" width="18" /></el-button></el-tooltip><el-tooltip v-if="hasAdd || hasSet || hasDelete" content="国家管理"><el-button link @click="countryManagerVisible = true"><Icon icon="solar:earth-outline" width="19" /></el-button></el-tooltip></div></div>
      <el-scrollbar class="country-list" v-loading="countriesLoading"><button v-for="item in countries" :key="item.country" class="country-item" :class="{ selected: item.country === selectedCountry }" @click="selectCountry(item.country)"><span>{{ item.country }}</span><el-tag size="small">{{ item.count }}</el-tag></button><el-empty v-if="!countriesLoading && !countries.length" description="暂无国家" /></el-scrollbar>
    </section>

    <section class="identity-list-panel">
      <div class="panel-header"><h2>{{ selectedCountry || '请选择国家' }}</h2><div v-if="selectedCountry" class="panel-actions"><el-tooltip content="刷新"><el-button link @click="loadIdentities"><Icon icon="ion:reload" width="18" /></el-button></el-tooltip><el-tooltip v-if="hasAdd" content="新建临时身份"><el-button type="primary" link @click="openCreate"><Icon icon="ion:add-outline" width="22" /></el-button></el-tooltip></div></div>
      <template v-if="selectedCountry"><el-input v-model="search" clearable placeholder="搜索姓名、邮箱、用户名、城市或地址" @input="searchIdentities"><template #prefix><Icon icon="solar:magnifer-outline" /></template></el-input><el-scrollbar v-loading="identitiesLoading" class="identity-list"><button v-for="identity in identities" :key="identity.rowkey" class="identity-card" :class="{ selected: identity.rowkey === selectedRowkey }" @click="selectIdentity(identity.rowkey)"><strong>{{ identity.fullName || identity.username || identity.rowkey }}</strong><span v-if="identity.gender">{{ identity.gender }}</span><span>{{ identity.temporaryMail || identity.username }}</span><small>{{ identity.address }}</small></button><el-empty v-if="!identitiesLoading && !identities.length" description="该国家暂无身份" /></el-scrollbar><el-pagination v-if="total > pageSize" background layout="prev, pager, next" :page-size="pageSize" :total="total" :current-page="page + 1" @current-change="changePage" /></template><el-empty v-else description="请先从左侧选择国家" />
    </section>

    <section class="identity-detail-panel" v-loading="detailLoading"><template v-if="detail"><div class="panel-header"><div><h2>{{ detail.Country }}身份资料</h2><div class="detail-name">{{ detail.Full_Name || detail.Username || detail.rowkey }}</div><span class="rowkey">{{ detail.rowkey }}</span></div><div class="panel-actions"><el-tooltip v-if="hasSet" content="编辑"><el-button link @click="openEdit"><Icon icon="solar:pen-outline" width="19" /></el-button></el-tooltip><el-tooltip v-if="hasDelete" content="删除"><el-button type="danger" link @click="deleteSelected"><Icon icon="uiw:delete" width="17" /></el-button></el-tooltip></div></div><section v-for="section in detailSections" :key="section.title" class="detail-section"><h3>{{ section.title }}</h3><div class="detail-rows"><div v-for="item in section.items" :key="item.key" class="detail-row"><span>{{ label(item.key) }}</span><strong>{{ item.value }}</strong><el-tooltip content="复制"><el-button link @click="copyValue(item.value)"><Icon icon="fluent:copy-20-regular" width="17" /></el-button></el-tooltip></div></div></section></template><el-empty v-else description="请选择身份卡片查看详情" /></section>

    <el-dialog v-model="countryManagerVisible" title="国家管理" width="560px"><div class="country-add" v-if="hasAdd"><el-input v-model="newCountry" placeholder="输入国家名称" @keyup.enter="addCountry" /><el-button type="primary" @click="addCountry">新增</el-button></div><el-table :data="countries"><el-table-column prop="country" label="国家" /><el-table-column prop="count" label="身份数量" width="100" /><el-table-column label="操作" width="120"><template #default="{ row }"><el-tooltip v-if="hasSet" content="编辑"><el-button link @click="openCountryEdit(row.country)"><Icon icon="solar:pen-outline" width="18" /></el-button></el-tooltip><el-tooltip :content="row.count ? '请先迁移或删除该国身份' : '删除'"><el-button v-if="hasDelete" type="danger" link :disabled="row.count > 0" @click="deleteCountry(row.country)"><Icon icon="uiw:delete" width="16" /></el-button></el-tooltip></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="countryEditVisible" title="编辑国家" width="400px"><el-input v-model="countryEditValue" placeholder="国家名称" /><template #footer><el-button @click="countryEditVisible = false">取消</el-button><el-button type="primary" @click="saveCountryEdit">保存</el-button></template></el-dialog>

    <el-dialog v-model="formVisible" :title="editing ? '编辑临时身份' : '新建临时身份'" width="min(880px, calc(100% - 32px))" @closed="resetForm"><el-scrollbar max-height="65vh"><el-form label-position="top"><el-form-item label="国家" required><el-select v-model="formCountry" filterable placeholder="请选择国家" style="width:100%"><el-option v-for="item in countries" :key="item.country" :label="item.country" :value="item.country" /></el-select></el-form-item><el-radio-group v-if="!editing" v-model="createMode" class="mode-switch"><el-radio-button value="manual">手动填写</el-radio-button><el-radio-button value="json">JSON 导入</el-radio-button></el-radio-group><el-input v-if="!editing && createMode === 'json'" v-model="jsonText" type="textarea" :rows="14" placeholder="粘贴单条 JSON 对象" class="json-input" /><template v-else><section v-for="section in formSections" :key="section.title" class="form-section"><h3>{{ section.title }}</h3><div class="form-grid"><el-form-item v-for="key in section.keys" :key="key" :label="label(key)"><el-input v-model="form[key]" :readonly="key === 'rowkey'" /></el-form-item></div></section></template></el-form></el-scrollbar><template #footer><el-button @click="formVisible = false">取消</el-button><el-button type="primary" :disabled="!formCountry" :loading="saving" @click="saveIdentity">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Icon } from '@iconify/vue';
import { hasPerm } from '@/perm/perm.js';
import { temporaryIdentityAdd, temporaryIdentityCountries, temporaryIdentityCountryAdd, temporaryIdentityCountryDelete, temporaryIdentityCountrySet, temporaryIdentityDelete, temporaryIdentityDetail, temporaryIdentityList, temporaryIdentitySet } from '@/request/temporary-identity.js';

const groups = [{ title: '基本资料', keys: ['Full_Name', 'Full_Name_Tran', 'Gender', 'Title', 'Birthday', 'Hair_Color'] }, { title: '地址', keys: ['Country', 'Address', 'Address_Alias', 'Trans_Address', 'Trans_Cn_Address', 'City', 'State', 'State_Full', 'Zip_Code', 'Telephone', 'Fax', 'Temporary_mail'] }, { title: '就业与信用卡', keys: ['Credit_Card_Type', 'Credit_Card_Number', 'CVV2', 'Expires', 'Occupation', 'Employment_Status', 'Monthly_Salary', 'Social_Security_Number'] }, { title: '更多资料', keys: ['Username', 'Password', 'Height', 'Weight', 'Blood_Type', 'System', 'GUID', 'Browser_User_Agent', 'Educational_Background', 'Website', 'Security_Question', 'Security_Answer'] }];
const labels = { Country: '国家', Full_Name: '全名', Full_Name_Tran: '全名翻译', Gender: '性别', Title: '称谓', Birthday: '生日', Hair_Color: '发色', Address: '地址', Address_Alias: '别名地址', Trans_Address: '地址翻译', Trans_Cn_Address: '中文地址', City: '城市', State: '州/省', State_Full: '州/省全称', Zip_Code: '邮编', Telephone: '电话', Fax: '传真', Temporary_mail: '临时邮箱', Credit_Card_Type: '信用卡类型', Credit_Card_Number: '信用卡号', CVV2: 'CVV2', Expires: '有效期', Occupation: '职业', Employment_Status: '就业状态', Monthly_Salary: '月薪', Social_Security_Number: '社会保障号', Username: '用户名', Password: '密码', Height: '身高', Weight: '体重', Blood_Type: '血型', System: '操作系统', GUID: 'GUID', Browser_User_Agent: '浏览器 User-Agent', Educational_Background: '教育背景', Website: '个人主页', Security_Question: '安全问题', Security_Answer: '问题答案', rowkey: '记录标识' };
const knownKeys = new Set(groups.flatMap(group => group.keys).concat('rowkey'));
const countries = ref([]); const countriesLoading = ref(false); const selectedCountry = ref(''); const identities = ref([]); const total = ref(0); const page = ref(0); const pageSize = 50; const search = ref(''); const identitiesLoading = ref(false); const selectedRowkey = ref(''); const detail = ref(null); const detailLoading = ref(false); const countryManagerVisible = ref(false); const newCountry = ref(''); const countryEditVisible = ref(false); const countryEditing = ref(''); const countryEditValue = ref(''); const formVisible = ref(false); const editing = ref(false); const saving = ref(false); const formCountry = ref(''); const createMode = ref('manual'); const jsonText = ref(''); const form = reactive({});
const hasAdd = hasPerm('temporary-identity:add'); const hasSet = hasPerm('temporary-identity:set'); const hasDelete = hasPerm('temporary-identity:delete');
const formSections = computed(() => editing.value ? [{ title: '记录标识', keys: ['rowkey'] }, ...groups] : groups);
const detailSections = computed(() => { if (!detail.value) return []; const toItem = key => ({ key, value: detail.value[key] }); const result = groups.map(group => ({ title: group.title, items: group.keys.filter(key => detail.value[key] !== undefined && detail.value[key] !== '').map(toItem) })); const extras = Object.keys(detail.value).filter(key => !knownKeys.has(key) && detail.value[key] !== '').map(toItem); if (extras.length) result.push({ title: '其他资料', items: extras }); return result.filter(section => section.items.length); });
function label(key) { return labels[key] || key; } function blank() { return Object.fromEntries(groups.flatMap(group => group.keys).filter(key => key !== 'Country').map(key => [key, ''])); }
async function loadCountries() { countriesLoading.value = true; try { countries.value = (await temporaryIdentityCountries()).list; if (selectedCountry.value && !countries.value.some(item => item.country === selectedCountry.value)) { selectedCountry.value = ''; identities.value = []; detail.value = null; } } finally { countriesLoading.value = false; } }
async function selectCountry(country) { selectedCountry.value = country; page.value = 0; search.value = ''; selectedRowkey.value = ''; detail.value = null; await loadIdentities(); }
async function loadIdentities() { if (!selectedCountry.value) return; identitiesLoading.value = true; try { const data = await temporaryIdentityList({ country: selectedCountry.value, q: search.value, limit: pageSize, offset: page.value * pageSize }); identities.value = data.list; total.value = data.total; } finally { identitiesLoading.value = false; } }
function searchIdentities() { page.value = 0; loadIdentities(); } function changePage(value) { page.value = value - 1; loadIdentities(); }
async function selectIdentity(rowkey) { selectedRowkey.value = rowkey; detailLoading.value = true; try { detail.value = await temporaryIdentityDetail(rowkey); } finally { detailLoading.value = false; } }
async function addCountry() { if (!newCountry.value.trim()) return; await temporaryIdentityCountryAdd(newCountry.value); newCountry.value = ''; await loadCountries(); }
function openCountryEdit(country) { countryEditing.value = country; countryEditValue.value = country; countryEditVisible.value = true; } async function saveCountryEdit() { const result = await temporaryIdentityCountrySet(countryEditing.value, countryEditValue.value); countryEditVisible.value = false; await loadCountries(); if (selectedCountry.value === countryEditing.value) await selectCountry(result.country); } async function deleteCountry(country) { await ElMessageBox.confirm(`删除国家“${country}”？`, { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await temporaryIdentityCountryDelete(country); await loadCountries(); }
function openCreate() { editing.value = false; formCountry.value = selectedCountry.value; createMode.value = 'manual'; jsonText.value = ''; Object.assign(form, blank()); formVisible.value = true; } function openEdit() { editing.value = true; formCountry.value = detail.value.Country; Object.assign(form, JSON.parse(JSON.stringify(detail.value))); formVisible.value = true; } function resetForm() { Object.keys(form).forEach(key => delete form[key]); }
function requestData() { if (!formCountry.value) return null; if (editing.value || createMode.value === 'manual') return { ...form }; try { const value = JSON.parse(jsonText.value); if (!value || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype || Object.values(value).some(item => typeof item !== 'string')) throw new Error('invalid'); return value; } catch { ElMessage({ type: 'error', message: 'JSON 格式错误，请输入单条字符串字段对象' }); return null; } }
async function saveIdentity() { const data = requestData(); if (!data) return; saving.value = true; try { const saved = editing.value ? await temporaryIdentitySet(detail.value.rowkey, formCountry.value, data) : await temporaryIdentityAdd(formCountry.value, data); formVisible.value = false; await loadCountries(); await selectCountry(saved.country); await selectIdentity(saved.rowkey); } finally { saving.value = false; } }
async function deleteSelected() { await ElMessageBox.confirm('删除当前身份？', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await temporaryIdentityDelete([selectedRowkey.value]); selectedRowkey.value = ''; detail.value = null; await loadIdentities(); await loadCountries(); }
async function copyValue(value) { try { await navigator.clipboard.writeText(String(value)); ElMessage({ type: 'success', message: '复制成功' }); } catch { ElMessage({ type: 'error', message: '复制失败' }); } }
onMounted(loadCountries);
</script>

<style scoped lang="scss">
.temporary-identities{display:grid;grid-template-columns:220px 320px minmax(0,1fr);height:100%;overflow:hidden}.country-panel,.identity-list-panel,.identity-detail-panel{min-width:0;padding:20px;overflow:auto;border-right:1px solid var(--el-border-color-lighter)}.identity-detail-panel{border:0}.panel-header{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:14px}.panel-header h2{margin:0;font-size:20px}.panel-actions,.country-add{display:flex;align-items:center;gap:6px}.country-list,.identity-list{height:calc(100% - 55px);margin-top:10px}.country-item,.identity-card{display:flex;width:100%;color:inherit;background:transparent;border:1px solid var(--el-border-color-lighter);border-radius:8px;cursor:pointer}.country-item{align-items:center;justify-content:space-between;padding:10px;margin-bottom:7px;text-align:left}.identity-card{flex-direction:column;gap:4px;padding:12px;margin-bottom:8px;text-align:left}.country-item.selected,.country-item:hover,.identity-card.selected,.identity-card:hover{border-color:var(--el-color-primary);background:var(--el-color-primary-light-9)}.identity-card span,.identity-card small,.rowkey{color:var(--el-text-color-secondary)}.detail-name{font-weight:600;margin:5px 0}.detail-section{margin-bottom:18px;border:1px solid var(--el-border-color-lighter);border-radius:6px;overflow:hidden}.detail-section h3{margin:0;padding:9px 12px;background:var(--el-color-primary);color:#fff;font-size:15px}.detail-row{display:grid;grid-template-columns:32% minmax(0,1fr) 34px;align-items:start;min-height:38px;border-top:1px solid var(--el-border-color-lighter)}.detail-row:first-child{border-top:0}.detail-row>span{padding:9px 12px;color:var(--el-text-color-secondary);background:var(--el-fill-color-lighter)}.detail-row>strong{padding:9px 12px;overflow-wrap:anywhere;white-space:pre-wrap}.country-add{margin-bottom:12px}.mode-switch{margin:0 0 18px}.json-input{margin-bottom:16px}.form-section{margin-bottom:22px}.form-section h3{font-size:15px;margin:0 0 10px}.form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:0 12px}@media(max-width:1024px){.temporary-identities{grid-template-columns:1fr minmax(280px,360px);grid-template-rows:180px minmax(0,1fr)}.country-panel{grid-column:1/-1;border-bottom:1px solid var(--el-border-color-lighter)}.country-list{height:105px}.identity-detail-panel{border-right:0}}@media(max-width:767px){.temporary-identities{display:block;overflow:auto}.country-panel,.identity-list-panel,.identity-detail-panel{min-height:330px;border-right:0;border-bottom:1px solid var(--el-border-color-lighter)}.country-list,.identity-list{height:220px}.detail-row{grid-template-columns:32% minmax(0,1fr) 34px}.detail-row>span,.detail-row>strong{padding:8px}.country-add{align-items:stretch;flex-direction:column}}
</style>
